# Generated by Django 4.0.5 on 2022-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=100)),
                ('RG', models.CharField(max_length=100)),
                ('Nascimento', models.DateField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Salario', models.FloatField(max_length=100)),
                ('Endereço', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=100)),
                ('CTPS', models.DateField(max_length=100)),
            ],
        ),
    ]
