# Generated by Django 4.0.5 on 2022-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente', models.CharField(max_length=100)),
                ('CPF_Paciente', models.CharField(max_length=100)),
                ('Medico', models.CharField(max_length=100)),
                ('CRM', models.CharField(max_length=100)),
                ('Data', models.DateField(max_length=100)),
                ('Valor', models.FloatField(max_length=100)),
            ],
        ),
    ]
